### ISSUE TITLE
Request to transfer ownership of repository

### ISSUE THREAD

**Issue by nirizr** [nirizr/vmsnparser#2]
Hi Steeve,

This repository is an exported repository from an old Google Code project of mine,
and I would like to maintain it and have ownership of the github repository (since as you know google code is dead).

I would like to politely request a transfer of ownership of this repository to my account, so I could mange and own it under my name.

Thank you for your consideration,
Nir.

**Comment by shiftre** [comment]
👍

**Comment by nirizr** [comment]
Great success!

Thanks again @steeve85
